# This is a basic workflow to help you get started with Actions

name: Trigger workflows using Git Actions REST API

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Trigger_Repo_Workflows:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Calls REST API using curl to trigger the workflows of other repos
      - name: REST API with curl
        run: |
          curl --location 'https://api.github.com/repos/trialuser543/test-repository/actions/workflows/65924802/dispatches' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer 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' \
          --data '{"ref": "main"}'

  trigger-CI-workflow:
    uses: trialuser543/test/.github/workflows/blank.yml@main
